steps:
  run:
    when:
      event: push
    image: gradle:7.6-jdk11-jammy
    commands:
      # Install Sequoia-SOP
      - apt update && apt install --yes sqop
      # Checkout code
      - git checkout $CI_COMMIT_BRANCH
      # Prepare CI
      - cp external-sop/src/main/resources/sop/testsuite/external/config.json.ci external-sop/src/main/resources/sop/testsuite/external/config.json
      # Code works
      - gradle test
      # Code is clean
      - gradle check javadocAll
      # Code has coverage
      - gradle jacocoRootReport coveralls
    environment:
      COVERALLS_REPO_TOKEN:
        from_secret: coveralls_repo_token
